### ISSUE TITLE
Jorge Mendoza W3 Project

### ISSUE THREAD

**Issue by jmgpgit** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#1]
https://github.com/jmgpgit/Database_Project

**Comment by fjgarciaes** [comment]
Excelente trabajo Jorge, un muy buen trabajo con las funciones que creaste y con todo el proceso en general, lo único que  no he visto la captura de las relaciones, el readme también muy bien explicado, trata de incluir iconos o alguna imagen para que sea mas visual si puedes. Sigue así :)
