### ISSUE TITLE
[Data-Base-Project] (Bea Zatarain)

### ISSUE THREAD

**Issue by BeaZatarain** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#10]
https://github.com/BeaZatarain/Data-Base-Project

**Comment by OrianAmpuero** [comment]
Muy bien Bea, todo organizado en el repo y el readme explicado (si luego te animas a ponerle más cariño y detalles mejor aún) jaja!! 💃😊 Sigamos así y animo esta semana
