### ISSUE TITLE
[w3-database-project] (Cristian Gómez)

### ISSUE THREAD

**Issue by crisgo-data** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#11]
https://github.com/crisgo-data/sql-data-base-building

**Comment by OrianAmpuero** [comment]
Muy bien Cristian!! El repo debería tener todos sus archivos organizados por carpetas y en cuanto al repo te animo a ponerle más cariño jaja... 
Con la presentación: 
-Mejorar el inicio (saludo...)
-Mucho texto en pantalla, intenta poner más imágenes o palabras claves
-Trata de no leer tanto y dirigirte mas a tus compis

De resto vas muy bien, así que sigamos así😊
