### ISSUE TITLE
[DataBase-Proyecto-2](Lohengrin Verde)

### ISSUE THREAD

**Issue by lohe040789** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#12]
https://github.com/lohe040789/DataBase-Proyecto-2

**Comment by fjgarciaes** [comment]
Buen trabajo Lohe!! Tanto el proceso de limpieza como las relaciones de SQL esta bien realizado y se ve que hay trabajo detrás. Trata de no poner código en el readme ya que hay gente que no sabe de código entonces trata de hacerlo más sencillo. En cuanto a la presentación te felicito por haberte esforzado en hacer una presentación y no únicamente usar el readme aunque estaría bien que como te dije antes no incluya tanto código, te has centrado mucho en el proceso a seguir pero muy bien por mostrar el diagrama y hablar sobre ello ya que era la parte mas importante. Sigue así :)

**Comment by lohe040789** [comment]
Oído ! Gracias Javi
Por más y mejor

Ing. Lohengrin Verde

El 7 feb 2023, a las 15:49, Javier Garcia Escobar ***@***.***> escribió:

﻿

Buen trabajo Lohe!! Tanto el proceso de limpieza como las relaciones de SQL esta bien realizado y se ve que hay trabajo detrás. Trata de no poner código en el readme ya que hay gente que no sabe de código entonces trata de hacerlo más sencillo. En cuanto a la presentación te felicito por haberte esforzado en hacer una presentación y no únicamente usar el readme aunque estaría bien que como te dije antes no incluya tanto código, te has centrado mucho en el proceso a seguir pero muy bien por mostrar el diagrama y hablar sobre ello ya que era la parte mas importante. Sigue así :)
