### ISSUE TITLE
BUSTBLOCKER (Santiago Fuentes)

### ISSUE THREAD

**Issue by santiagofp9** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#15]
https://github.com/santiagofp9/BUSTBLOCKER

**Comment by fjgarciaes** [comment]
Buen trabajo! No veo el archivo en el que se supone que están las querys y seria interesante poder ver una captura de las relaciones creadas en SQL con el diagrama ademas dale una vuelta al readme ya que es muy corto y deberia ser explicativo del proceso que has seguido :)

**Comment by santiagofp9** [comment]
Hola Javí!

Acabo de darme cuenta que llevaba un par de días haciendo stash en lugar de
push en forma. En el repo se puede ver que están los últimos archivos
modificados hace 8 horas, salvo una imagen del diagrama de la base de
datos, que acabo de tomar y agregar.

Serías tan amable de echarle otro ojo al repo?

Disculpa :S

**Comment by fjgarciaes** [comment]
Ya lo he mirado, gracias. El diagrama y las querys están bien, lo único que si te das cuenta podías relacionar rental con inventory ya que rental tiene inventory_id pero el resto esta bien.

**Comment by santiagofp9** [comment]
Gracias! Sí lo vi, pero decidí mantenerlo fuera porque lo único que me
servía de ahí era una posible lista de los mejores clientes.
