### ISSUE TITLE
[w3-database-project](Paula Bendito Buhles)

### ISSUE THREAD

**Issue by paulabnbh** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#2]
https://github.com/paulabnbh/Database-project-SQL

**Comment by fjgarciaes** [comment]
Excelente trabajo Paula! Vi tu esfuerzo el viernes y se nota que tiene un trabajo con sentido detrás. Tanto la limpieza como todo el proceso de SQL están muy bien y con sentido, te has esforzado en perfeccionar el ERD aunque el que ya tenias te sirviese y eso demuestra una actitud muy buena y trabajadora por tu parte así que te felicito por ello.
En cuanto a la presentación has hablado un poco rápido así que para la próxima intenta centrarte en eso, bien por enseñar y explicar el diagrama y por no hablar de código. 

Has hecho un trabajo excelente en todo este proyecto así que sigue así que es el buen camino! :)
