### ISSUE TITLE
[w3-database-project](Cristina Apostol)

### ISSUE THREAD

**Issue by cristina-apostol** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#20]
https://github.com/cristina-apostol/Proyecto-SQL.git

**Comment by OrianAmpuero** [comment]
Muy bien Cristina😊!! Excelente trabajo, readme, repo en general; se nota el curro en cuanto a las relaciones y todo el análisis detrás. Sigue así que vas muy bien💃
