### ISSUE TITLE
[w3-database-project](ruben.francisco)

### ISSUE THREAD

**Issue by segomismo** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#21]
https://github.com/segomismo/2-proj-cineclub.git

**Comment by fjgarciaes** [comment]
Buen trabajo Ruben! Se ve que has trabajado tanto el proceso de limpieza como en SQL ( llegando a complicarte un poco mas de lo necesario en este caso jaja) a la hora de crear las relaciones deberían estar todas las tablas unidas para poder acceder a ellas y en el readme revisa por que la imagen no se ve y trata de hacerlo un poco mas vistoso si puedes. Sigue trabajando y esforzándote así :)
