### ISSUE TITLE
SQL Blockbuster (Fernando Amaya)

### ISSUE THREAD

**Issue by Patacabra** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#22]
https://github.com/Patacabra/SQLBuster.git

**Comment by OrianAmpuero** [comment]
Buen trabajo Fer! En cuanto al repo, debería estar organizado cada archivo en su respectiva carpeta, adjuntar el ERD y hacer el readme que es tu carta de presentación. Sé que puedes con esto y más, así que te animo a trabajar en ello😊.
En la presentación:
-Mejorar el inicio (con saludo...)
-Trata de no decir lo malo porque nadie lo sabe
-Tener un apoyo visual ya que es día de presentación y hay que prepararse
-Cuidado con las relaciones (pensar bien la lógica que debe tener por general)
-No leer tanto la pantalla y dirigirte mas a tus compis
-Cuidado con los brazos cerrados y la postura
