### ISSUE TITLE
pgmar257/sql-data-base-building(Paula-Garcia)

### ISSUE THREAD

**Issue by pgmar257** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#24]

**Comment by fjgarciaes** [comment]
Buen trabajo Paula, echale un ojo a las relaciones ya que creaste muchas foreing key (creo que por error)  y si puedes incluye el diagrama en el readme para hacerlo mas vistoso. Se nota el esfuerzo, sigue así :)
