### ISSUE TITLE
Project 2 - Axel Girou

### ISSUE THREAD

**Issue by AxelCrypto** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#3]
https://github.com/AxelCrypto/Data-Base-Creation.git

**Comment by OrianAmpuero** [comment]
Bien Axel! En cuanto al repo, trata de organizar todos los archivos en carpetas, borrar lo que sobra y solo tener arriba en el github lo realmente necesario, CUIDADO (has subido tu contraseña), así que modifica el repo para que no tengas problemas; en cuanto al readme ponle mas color y un poco más llamativo.
