### ISSUE TITLE
[database-project](Alvaro Lorenzo)

### ISSUE THREAD

**Issue by alorenzoti** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#6]
https://github.com/alorenzoti/database_proyect

**Comment by OrianAmpuero** [comment]
Muy bien Álvaro! Le puedes poner más cariño al readme pero de resto bien organizado el repo. En cuanto a la presentación:
-Mejorar el inicio de la presentación 
-Tener mejor actiud para explicar el proyecto
-Tratar de no decir lo malo porque nadie lo sabe
-Muy rápido (ni tanto ni tan poco) jaja
💃
