### ISSUE TITLE
[SQL-Proyect](Pedro Jódar)

### ISSUE THREAD

**Issue by Periclates7** [Ironhack-Data-Madrid-Enero-2023/w3-database-project#7]

**Comment by Periclates7** [comment]
https://github.com/Periclates7/SQL-Proyect

**Comment by fjgarciaes** [comment]
Muy buen trabajo Pedro! Te has esforzado en la limpieza y en el proceso de SQL así que te felicito por el esfuerzo, como detalle, en algunas tablas, si has creado el nombre completo puedes eliminar los datos de nombre y apellidos ya que no los vas a necesitar. Vas por muy buen camino, sigue así :)
